name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build the Middleman site
      run: |
        gem install bundler
        bundle install --path vendor --jobs 4 --retry 3
        bundle exec middleman build --build-dir=public --clean
